apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eg-ingress-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eg-ingress-controller
      name: eg-ingress-controller
    spec:
      containers:
        - name: eg-ingress-controller
          image: eg-ingress-controller
          imagePullPolicy: Never
          readinessProbe: &probe
              httpGet:
                host: localhost
                path: /users
                port: 9876
              initialDelaySeconds: 10
              periodSeconds: 3
          livenessProbe: &probe
          env:
            - name: DEBUG
              value: 'eg-ingress-controller*'
        - name: express-gateway
          image: expressgateway/express-gateway
          readinessProbe: *probe
          livenessProbe: *probe
          env:
            - name: LOG_LEVEL
              value: debug
